# Default update config
# Config order: hparams_registry -> config.yaml -> CLI
swad: True  # True / False
swad_kwargs:
  n_converge: 3
  n_tolerance: 6
  tolerance_ratio: 0.3
test_batchsize: 128

# resnet50, resnet50_barlowtwins, resnet50_moco, clip_resnet50, clip_vit-b16, swag_regnety_16gf
model: resnet50
feat_layers: stem_block

# MIRO params
ld: 0.1  # lambda
lr_mult: 10.

use_condition1: True
use_condition2: True
shift: 0.0
d_shift: 0.0
use_MIRO: True
MDA: 0.0
mask_range: 0.0
confidence: 0.0
confidence_ratio: 0.0
low_degree: 0.0
setting_name: None
#use_MIRO: False